version: "3.3"
services:
  orionrepeater:
    build: ./node
    environment:
      - LISTEN_PORT=8080
      - LISTEN_IP=0.0.0.0 
      - TARGET_ORION_URL=http://127.0.0.1:1026
      - TARGET_SERVICE=default
      - TARGET_SERVICE_PATH=/
      - TARGET_AUTH_TOKEN_FILE=/run/secrets/orionrepeater.auth.token
    ports:
      - "8080:8080" 
      - "9229:9229"
    volumes:
      - ..:/app
    secrets:
      - orionrepeater.auth.token
secrets:
    orionrepeater.auth.token:
        file: ./secrets/orionrepeater.auth.token